#!/bin/bash


# All the files

/media/ubuntu/GC_2TB/work/geocities/ar.geocities.com
/media/ubuntu/GC_2TB/work/geocities/ar.geocities.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/ar.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/ar.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/asia.geocities.com
/media/ubuntu/GC_2TB/work/geocities/asia.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/au.geocities.com
/media/ubuntu/GC_2TB/work/geocities/au.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/br.geocities.com
/media/ubuntu/GC_2TB/work/geocities/br.noticias.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/br.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/br.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/ca.geocities.com
/media/ubuntu/GC_2TB/work/geocities/ca.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/cf.geocities.com
/media/ubuntu/GC_2TB/work/geocities/chat.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/de.geocities.com
/media/ubuntu/GC_2TB/work/geocities/dir.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/docs.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/es.geocities.com
/media/ubuntu/GC_2TB/work/geocities/espanol.geocities.com
/media/ubuntu/GC_2TB/work/geocities/features.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/finance.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/financevision.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/games.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/gargantuageocities.com
/media/ubuntu/GC_2TB/work/geocities/geo.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/geocities.yahoo.co.jp
/media/ubuntu/GC_2TB/work/geocities/geocities.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/geocities4ever.com
/media/ubuntu/GC_2TB/work/geocities/green.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/help.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/hk.geocities.com
/media/ubuntu/GC_2TB/work/geocities/hk.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/in.geocities.com
/media/ubuntu/GC_2TB/work/geocities/info.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/it.geocities.com
/media/ubuntu/GC_2TB/work/geocities/kr.geocities.com
/media/ubuntu/GC_2TB/work/geocities/login.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/mx.geocities.com
/media/ubuntu/GC_2TB/work/geocities/mx.geocities.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/mx.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/news.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/p1.geo.sp2.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/p2.geo.sp2.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/p3.geo.sp2.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/pages.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/pic.geocities.com
/media/ubuntu/GC_2TB/work/geocities/picks.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/rivals.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/search.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/sg.geocities.com
/media/ubuntu/GC_2TB/work/geocities/share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/shopping.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/smallbusiness.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/sports.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/themis.geocities.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/tournament.fantasysports.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/travel.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/tv.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/uk.geocities.com
/media/ubuntu/GC_2TB/work/geocities/uk.geocities.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/uk.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p2.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p3.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p4.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p5.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p7.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p8.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p9.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p10.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.1.p12.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.2.p2.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.geocities.com
/media/ubuntu/GC_2TB/work/geocities/us.geocities.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/us.share.geocities.com
/media/ubuntu/GC_2TB/work/geocities/visit.geocities.com
/media/ubuntu/GC_2TB/work/geocities/visit.geocities.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/weather.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/www.geocities.com
/media/ubuntu/GC_2TB/work/geocities/www.yahoo.com
/media/ubuntu/GC_2TB/work/geocities/yahoopagebuilderhelp.com
